[book]
authors = ["kurteklund"]
language = "en"
multilingual = false
src = "src"
title = "Kurt-Roger"

[build]
build-dir = "docs" 

[output.html]
additional-css = ["bridge.css"]

[preprocessor.example]
command = "node /home/kurt/js/typescript/mdbook-bridge-preprocessor/mdbook-bridge-preprocessor.js"
renderer = ["html"] 
